//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerveCentre.App_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupDisplay
    {
        public int ID { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public Nullable<int> TelevisionId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string ResourcePath { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Factory Factory { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Television Television { get; set; }
    }
}
